name: live_music
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^6.1.5
  video_player: ^2.7.2

  flutter_bloc: ^9.1.0
  firebase_messaging: ^15.2.4
  logger: ^2.5.0
  image_cropper: ^9.0.0
  permission_handler: ^11.4.0
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  flutter_svg: ^2.0.9
  rxdart: ^0.28.0
  flutter_riverpod: ^2.6.1
  multi_select_flutter: ^4.1.3
  floor: ^1.4.2
  sqflite: ^2.3.0
  floor_generator: ^1.1.0
  provider: ^6.1.3
  build_runner: ^2.1.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_chat_bubble: ^2.0.2
  dio: ^4.0.0
  path_provider: ^2.1.1
  shared_preferences: ^2.0.0
  intl: ^0.20.2
  go_router: ^6.0.3
  flutter_hooks: ^0.18.0
  flutter_plugin_android_lifecycle: ^2.0.7
  image_picker: ^0.8.4+3
  firebase_core: ^3.12.1
  flutter_picker: ^2.0.0
  firebase_crashlytics: ^4.3.5
  http: ^1.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  firebase_database: ^11.3.4
  table_calendar: ^3.0.8
  url_launcher: ^6.0.20
  google_maps_flutter: ^2.2.0
  cached_network_image: ^3.2.0
  fluttertoast: ^8.2.2
  flutter_launcher_icons: ^0.14.3
  
flutter_launcher_icons:
  image_path_android: "assets/images/LiveMusic_ic.png"
  image_path_ios: "assets/images/LiveMusicIos_ic.jpg"
  android: true
  ios: true
  adaptive_icon_background: "assets/images/LiveMusic_ic.png"
  adaptive_icon_foreground: "assets/images/transparent.png"

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
    - shorebird.yaml
  fonts:
    - family: BeVietnamPro
      fonts:
        - asset: assets/fonts/bevietnamproregular.ttf
          weight: 400
        - asset: assets/fonts/bevietnamprobold.ttf
          weight: 700
